### ISSUE TITLE
standardize the district data

### ISSUE THREAD

**Issue by rgdonohue** [chrispappas007/confedmont#15]
I guess we probably should. Something like this?

![image](https://user-images.githubusercontent.com/1952205/32531917-f48ed28a-c403-11e7-90ee-144a3efff6e6.png)

**Comment by chrispappas007** [comment]
I guess so? how is this working? is it summing districts to get to 1000 m2 and adding up the number of monuments? the numbers are weird too - i don't think there's more than 1200 or 1300 monuments.

**Comment by rgdonohue** [comment]
Yeah I was just dividing by the area and multiplying by some large number. Was too tired to do the math in my head and unsure of what ALAND units really are ... guessing square kms.

See [ce72900](https://github.com/chrispappas007/confedmont/commit/ce72900bd3f06e7411099528100a08ff228813ae)

**Comment by rgdonohue** [comment]
Having ".0003" monuments per 1000 sqr km is less striking perhaps. Could do by population or something I suppose (would involve more data/census processing, ugh). Monuments per Chick-fil-A restaurants?

I just know we'll get yelled at by the map police if we don't standardize.

**Comment by chrispappas007** [comment]
Difficulties in finding a good normalizing value so this is being set aside for now.
