### ISSUE TITLE
deal with too many markers

### ISSUE THREAD

**Issue by rgdonohue** [chrispappas007/confedmont#2]
Well ... I see an initial spatial pattern here across the US ...

![image](https://user-images.githubusercontent.com/1952205/32355928-72879886-bff7-11e7-9552-3b84a8119fcb.png)

**Comment by chrispappas007** [comment]
Um...wow. 
Initial thought is to group by state and then have it break apart as you zoom. 
Thoughts on marking states as union, confederate, or not recognized as a state at start of war?

**Comment by rgdonohue** [comment]
Has been clustered.
