### ISSUE TITLE
add election and demographic data to district.json

### ISSUE THREAD

**Issue by chrispappas007** [chrispappas007/confedmont#6]
The Daily Kos compiled election results and demographics by congressional district. There's a csv file in the project-data folder called 115CongressEdited.csv. There's good deal of data in there - what do we want to include? The file includes election results from the last couple of elections and the 2010 census demographic data. I think at the very least we should include party affiliation of the House Rep. Do we want to include any demographic data? Presidential election results (list party not name)? Thoughts??

**Comment by rgdonohue** [comment]
I'll have a look later this eve. We're risking trying to bring in too much data. Prob best to tie it up and make it simple/effective?

**Comment by chrispappas007** [comment]
you're probably right. And we would once again find ourselves on the slippery slope of correlation=causation. I just really like stirring the pot...

**Comment by chrispappas007** [comment]
Here's a thought - include what side the state was on. I think that's an interesting bit of info.

**Comment by rgdonohue** [comment]
yes. that info was in the original dataset?

**Comment by rgdonohue** [comment]
Okay, sorry. Just looking at this Daily Kos data now. Would take a little bit of annoying wrangling to tie it to our cartographic boundary file districts because they remoted leading zeros on FIPS.

I guess could standardize by Total Voting Age population?

Or scratch the choropleth and symbolize the districts red/blue.

**Comment by chrispappas007** [comment]
This data would require considerable wrangling to be used so we're abandoning it for now.
