### ISSUE TITLE
getColors only gets one color

### ISSUE THREAD

**Issue by chrispappas007** [chrispappas007/confedmont#9]
have created breaks to color choropleth but it has decided to only color the districts with one color. I can see in console that all my data is coming in. I removed 0 values from clustering and coded the 0 in on its own - not sure if this is what the problem is. BUT, i think having the 0 be it's own color will be better aesthetically. I'm sure it's something minor that i'm missing but i'm just not seeing it. I also thought about trying to color the districts by making a json but I wasn't sure how to assign each color to each break, and just hard coding them seemed to be about the same amount of work.

**Comment by rgdonohue** [comment]
needed `(d==0)`
